import { Meta } from '@storybook/angular/types-6-0';
import { color, withKnobs } from '@storybook/addon-knobs';
import { ChartComponent } from './chart/chart.component';
import { ChartModule } from './chart.module';
import {
  points1,
  points2,
} from '../../../components/src/component/chart/chart-data';
import { IChartConfig } from './model/i-chart-config';
import { AxisType } from './model/axis-type';
import { SeriesType } from './model/series-type';
import { randomInt } from 'd3-random';

export default {
  title: 'Component/Chart',
  decorators: [withKnobs],
  component: ChartComponent,
  moduleMetadata: {
    imports: [ChartModule],
  },
} as Meta;

const cssColorNames = [
  'AliceBlue',
  'AntiqueWhite',
  'Aqua',
  'Aquamarine',
  'Azure',
  'Beige',
  'Bisque',
  'Black',
  'BlanchedAlmond',
  'Blue',
  'BlueViolet',
  'Brown',
  'BurlyWood',
  'CadetBlue',
  'Chartreuse',
  'Chocolate',
  'Coral',
  'CornflowerBlue',
  'Cornsilk',
  'Crimson',
  'Cyan',
  'DarkBlue',
  'DarkCyan',
  'DarkGoldenRod',
  'DarkGray',
  'DarkGrey',
  'DarkGreen',
  'DarkKhaki',
  'DarkMagenta',
  'DarkOliveGreen',
  'DarkOrange',
  'DarkOrchid',
  'DarkRed',
  'DarkSalmon',
  'DarkSeaGreen',
  'DarkSlateBlue',
  'DarkSlateGray',
  'DarkSlateGrey',
  'DarkTurquoise',
  'DarkViolet',
  'DeepPink',
  'DeepSkyBlue',
  'DimGray',
  'DimGrey',
  'DodgerBlue',
  'FireBrick',
  'FloralWhite',
  'ForestGreen',
  'Fuchsia',
  'Gainsboro',
  'GhostWhite',
  'Gold',
  'GoldenRod',
  'Gray',
  'Grey',
  'Green',
  'GreenYellow',
  'HoneyDew',
  'HotPink',
  'IndianRed',
  'Indigo',
  'Ivory',
  'Khaki',
  'Lavender',
  'LavenderBlush',
  'LawnGreen',
  'LemonChiffon',
  'LightBlue',
  'LightCoral',
  'LightCyan',
  'LightGoldenRodYellow',
  'LightGray',
  'LightGrey',
  'LightGreen',
  'LightPink',
  'LightSalmon',
  'LightSeaGreen',
  'LightSkyBlue',
  'LightSlateGray',
  'LightSlateGrey',
  'LightSteelBlue',
  'LightYellow',
  'Lime',
  'LimeGreen',
  'Linen',
  'Magenta',
  'Maroon',
  'MediumAquaMarine',
  'MediumBlue',
  'MediumOrchid',
  'MediumPurple',
  'MediumSeaGreen',
  'MediumSlateBlue',
  'MediumSpringGreen',
  'MediumTurquoise',
  'MediumVioletRed',
  'MidnightBlue',
  'MintCream',
  'MistyRose',
  'Moccasin',
  'NavajoWhite',
  'Navy',
  'OldLace',
  'Olive',
  'OliveDrab',
  'Orange',
  'OrangeRed',
  'Orchid',
  'PaleGoldenRod',
  'PaleGreen',
  'PaleTurquoise',
  'PaleVioletRed',
  'PapayaWhip',
  'PeachPuff',
  'Peru',
  'Pink',
  'Plum',
  'PowderBlue',
  'Purple',
  'RebeccaPurple',
  'Red',
  'RosyBrown',
  'RoyalBlue',
  'SaddleBrown',
  'Salmon',
  'SandyBrown',
  'SeaGreen',
  'SeaShell',
  'Sienna',
  'Silver',
  'SkyBlue',
  'SlateBlue',
  'SlateGray',
  'SlateGrey',
  'Snow',
  'SpringGreen',
  'SteelBlue',
  'Tan',
  'Teal',
  'Thistle',
  'Tomato',
  'Turquoise',
  'Violet',
  'Wheat',
  'White',
  'WhiteSmoke',
  'Yellow',
  'YellowGreen',
];

const randomColor = randomInt(0, cssColorNames.length - 1);

const config: IChartConfig = {
  name: '123',
  xAxis: [
    {
      type: AxisType.time,
      visible: true,
    },
    {
      type: AxisType.number,
      visible: true,
      opposite: true,
      min: 1,
      max: 1500,
    },
  ],
  yAxis: [
    {
      type: AxisType.number,
      visible: true,
      title: 'атм',
    },
    {
      type: AxisType.number,
      visible: true,
      min: -500,
      max: 10000,
      title: 'кг/см2',
    },
    {
      type: AxisType.number,
      visible: true,
      min: -200,
      max: 200,
    },
    {
      type: AxisType.number,
      visible: true,
      min: 5000,
      max: 7000,
      opposite: true,
    },
    {
      type: AxisType.number,
      visible: true,
      min: -0.05,
      max: 0.05,
      opposite: true,
      title: 'тн',
    },
    {
      type: AxisType.log,
      visible: true,
      min: 1000000,
      max: 2000000,
    },
  ],
  series: [
    {
      type: SeriesType.line,
      data: points1,
      name: 'Series 1',
      xAxisIndex: 0,
      yAxisIndex: 0,
      color: cssColorNames[randomColor()].toLowerCase(),
      strokeWidth: 2,
    },
    {
      type: SeriesType.line,
      data: points2.map((point) => {
        return { ...point, color: cssColorNames[randomColor()] };
      }),
      name: 'Series 2',
      xAxisIndex: 0,
      yAxisIndex: 0,
      strokeWidth: 1.5,
      color: cssColorNames[randomColor()].toLowerCase(),
    },
  ],
};

export const basicChart = () => ({
  moduleMetadata: {
    imports: [ChartModule],
  },
  props: {
    config,
  },
  template: `<div class="font-body-3 padding-3 bg-background-0" style="width: auto; height: 600px;">
      <teta-chart [config]="config" class="bg-background-50 border border-text-50"></teta-chart>
    </div>`,
});
