name: Build & Release
on:
 # push:
  #  branches: [ main ]
  #pull_request:
   # branches: [ main ]
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: npm
          node-version: 16
      - name: Install and Build
        run: yarn && yarn global add @angular/cli && ng build components
      - name: Package
        run: yarn pack --prefix dist/components
        
      - name: Publish
        run: cd dist/components && npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.TETACOM_NPM_TOKEN }}
