name: Storybook
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
        with:
          persist-credentials: false
      - uses: actions/setup-node@v2
        with:
          cache: npm
          node-version: 16
      - name: Install & Build
        run: yarn && yarn global add @angular/cli
      - name: Deploy To Github Pages
        run: npx -p @storybook/storybook-deployer storybook-to-ghpages --branch gh-pages --source-branch main --ci true
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
