name: Storybook
on:
  pull_request:
    types: [closed]
    branches: [main]
  workflow_dispatch:
jobs:
  release:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
        with:
          persist-credentials: false
      - uses: actions/setup-node@v2
        with:
          cache: npm
          node-version: 18
#      - name: Install
#        run: yarn && yarn global add @angular/cli
      - name: Build
        run: npm install && npx nx run components:build-storybook
      - name: Deploy To Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/storybook
