name: Build & Release
on:
  pull_request:
    types: [closed]
    branches: [main]
  workflow_dispatch:
jobs:
  release:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
        with:
          persist-credentials: false
      - uses: actions/setup-node@v2
        with:
          cache: npm
          node-version: 16
      - name: Install & Build
        run: yarn && yarn global add @angular/cli && ng build components
      - name: Publish
        run: cd dist/components && npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.TETACOM_NPM_TOKEN }}
      - name: Deploy To Github Pages
        run: npx -p @storybook/storybook-deployer storybook-to-ghpages --branch gh-pages --source-branch main --ci true
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
