name: Release Components to NPM
on:
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
        with:
          token: ${{ secrets.GH_TOKEN }}
      - uses: actions/setup-node@v2
        with:
          cache: npm
          node-version: 18
      - name: Install & Build
        run: npm install && nxp nx build components
      - name: Publish
        run: cd projects/components && rm -f *.* && rm -r src && cp -r ./dist/* . && rm -rf dist && npx semantic-release -e semantic-release-monorepo
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.TETACOM_NPM_TOKEN }}
